stages:
    - build
    - deploy

image: tiangolo/docker-with-compose

job_build_staging:
    stage: build
    script:
      - docker-compose -p alanno_stage -f docker-compose.stage.yml build
    except:
      - master
    tags:
      - snjezana

job_deploy_staging:
    stage: deploy
    script:
      - docker-compose -p alanno_stage -f docker-compose.stage.yml down
      - docker-compose -p alanno_stage -f docker-compose.stage.yml up -d
    except:
      - master
    tags:
      - snjezana


job_build_prod:
    stage: build
    script:
      - docker-compose -p alanno_prod -f docker-compose.prod.yml build
    only:
      - master
    tags:
      - snjezana

job_deploy_prod:
    stage: deploy
    script:
      - docker-compose -p alanno_prod -f docker-compose.prod.yml down
      - docker-compose -p alanno_prod -f docker-compose.prod.yml up -d
    only:
      - master
    tags:
      - snjezana



