services:
    backend:
        build:
            dockerfile: deployment/django.prod.dockerfile
            context: .
        environment:
            DJANGO_SECRET_KEY: ${DJANGO_SECRET_KEY}
            DJANGO_DEBUG: "False"
            ALANNO_DB_NAME: ${ALANNO_DB_NAME}
            ALANNO_DB_USER: ${ALANNO_DB_USER}
            ALANNO_DB_HOST: ${ALANNO_DB_HOST}
            ALANNO_DB_PASSWORD: ${ALANNO_DB_PASSWORD}
            DJANGO_ADMIN_USERNAME: ${DJANGO_ADMIN_USERNAME}
            DJANGO_ADMIN_EMAIL: ${DJANGO_ADMIN_EMAIL}
            DJANGO_ADMIN_PASSWORD: ${DJANGO_ADMIN_PASSWORD}
        deploy:
            resources:
                reservations:
                    devices:
                        - driver: nvidia
                          capabilities: [ gpu ]
        depends_on:
            - database
        volumes:
            - django_static:/var/www/alanno/static/

    frontend:
        build:
            dockerfile: deployment/webpack.prod.dockerfile
            context: .
        depends_on:
            - backend

    nginx:
        build:
            dockerfile: deployment/nginx.prod.dockerfile
            context: .
        deploy:
            resources:
                limits:
                    cpus: 0.50
                    memory: 8G
        volumes:
            - django_static:/var/www/alanno/static/
        ports:
            - 8024:80

    database:
        image: postgres:12
        ports:
            - 5432:5432
        environment:
            POSTGRES_DB: ${ALANNO_DB_NAME}
            POSTGRES_USER: ${ALANNO_DB_USER}
            POSTGRES_PASSWORD: ${ALANNO_DB_PASSWORD}
        volumes:
            - postgres_persistence:/var/lib/postgresql/data

    redis:
        image: redis:alpine

    memcached:
        image: memcached
        ports:
            - 11211:11211
        environment:
            m: 1024 # 1GB for caching

    celery_default:
        build:
            dockerfile: deployment/django.prod.dockerfile
            context: .
        command: celery -A app worker -l INFO -Q celery
        depends_on:
            - backend
            - redis
            - memcached
        environment:
            CELERY_BROKER: "redis://redis:6379/0"
            CELERY_BACKEND: "redis://redis:6379/0"
            ALANNO_DB_NAME: ${ALANNO_DB_NAME}
            ALANNO_DB_USER: ${ALANNO_DB_USER}
            ALANNO_DB_HOST: ${ALANNO_DB_HOST}
            ALANNO_DB_PASSWORD: ${ALANNO_DB_PASSWORD}
        volumes:
            - django_static:/var/www/alanno/static/

    celery_al:
        build:
            dockerfile: deployment/django.prod.dockerfile
            context: .
        command: celery -A app worker -l INFO -Q al_loop --pool=solo
        depends_on:
            - backend
            - redis
            - memcached
        environment:
            CELERY_BROKER: "redis://redis:6379/0"
            CELERY_BACKEND: "redis://redis:6379/0"
            ALANNO_DB_NAME: ${ALANNO_DB_NAME}
            ALANNO_DB_USER: ${ALANNO_DB_USER}
            ALANNO_DB_HOST: ${ALANNO_DB_HOST}
            ALANNO_DB_PASSWORD: ${ALANNO_DB_PASSWORD}
        deploy:
            resources:
                reservations:
                    devices:
                        - driver: nvidia
                          capabilities: [ gpu ]
        volumes:
            - django_static:/var/www/alanno/static/

volumes:
    django_static: null
    postgres_persistence: null
